### ISSUE TITLE
Error: pluginOptions fields must be an object.. Help

### ISSUE THREAD

**Issue by jonasmarco** [alampros/gatsby-starter-grommet#2]
Hello
I'm starting a new projetct 

`gatsby new my-grommet-site https://github.com/alampros/gatsby-starter-grommet`
`cd my-grommet-site`
`npm i`
`gatsby build `
and I'm receiving this error:

Error: pluginOptions fields must be an object with field names as keys or a function which returns such an object.
  - Array.forEach
  - Array.forEach
  - Array.forEach
  - Array.forEach
  - Array.reduce
  - index.js:52 _callee$
    [gtb]/[gatsby]/dist/schema/index.js:52:20

**Comment by DDeme** [comment]
same for me

**Comment by HughZurname** [comment]
same here

**Comment by jonasmarco** [comment]
@DDeme @HughZurname sad :(
